# Generated by Django 2.2.4 on 2019-08-25 07:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identificator', models.CharField(max_length=16)),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('passport', models.CharField(max_length=64, verbose_name='Номер паспорта')),
            ],
            options={
                'ordering': ('identificator',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('theme', models.CharField(max_length=8, verbose_name='Тема')),
                ('short_description', models.TextField()),
                ('number_of_investors', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.Account')),
                ('investors', models.ManyToManyField(related_name='investors', to='accounts.Account')),
            ],
            options={
                'ordering': ('theme', '-number_of_investors'),
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='None')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Project')),
            ],
        ),
    ]
